Model: Ref
Variant: scalar_rgb # only for Mitsuba3

Scene: Liver-SingleMesh

Resolution:
  Width: 1920
  Height: 1080
Samples Per Pixel: 256
Max Depth : 12

Glisson Capsule:
  collagen_d: 3.5
  collagen_nMed: 1.35
  collagen_nP: 1.5
  collagen_vf1: 0.949
  collagen_vf2: 0.810
  collagen_vf3: 0.001
  collagen_vf4: 0.007
  elastin_d: 0.5
  elastin_nMed: 1.35
  elastin_nP: 1.534
  elastin_vf1: 0.051
  elastin_vf2: 0.189
  elastin_vf3: 0.254
  elastin_vf4: 0.087

Parenchyma:
  blood_vf: 0.004
  blood_St02: 0.9084
  blood_r: 0.004
  bile_vf: 0.0005
  lipid_vf: 0.289
  water_vf: 0.7
  hepatocity_vf: 0.8
  hepatocity_lAxis: 0.0020
  hepatocity_gAxis: 0.0030
  